//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaqueteriaWS.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estafeta
    {
        public int id { get; set; }
        public string CodigoPostal { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string periodisidad { get; set; }
        public string forzoso { get; set; }
        public string reexpedicion { get; set; }
        public string entregaFinSemana { get; set; }
        public string horarioExtendido { get; set; }
        public string lunes { get; set; }
        public string martes { get; set; }
        public string miercoles { get; set; }
        public string jueves { get; set; }
        public string viernes { get; set; }
        public string sabado { get; set; }
        public string domingo { get; set; }
    }
}
