//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaqueteriaWS.Models.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaqueteriasEntities : DbContext
    {
        public PaqueteriasEntities()
            : base("name=PaqueteriasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaqueteExpress> PaqueteExpress { get; set; }
        public virtual DbSet<Sendex> Sendex { get; set; }
        public virtual DbSet<Estafeta> Estafeta { get; set; }
    }
}
