//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaqueteriaWS.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteExpress
    {
        public int id { get; set; }
        public string CodigoPostal { get; set; }
        public string origen { get; set; }
        public string sucursal { get; set; }
        public string municipio { get; set; }
        public string ciudad { get; set; }
        public string colonia { get; set; }
        public string estado { get; set; }
        public string cobertura { get; set; }
    }
}
